#!/usr/bin/env python3
"""The sidebar and `docs/` must agree, judged on what is COMMITTED.

Starlight fails the build on a sidebar slug with no page, so an entry added
without its document takes the whole docs site down -- and it does so only in
CI, because the author's working tree has the file. That is the failure this
guards: `git ls-files`, not the filesystem, decides what exists.

The reverse direction is a lesser fault with the same cause: a document nobody
can navigate to is one nobody reads.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "website" / "astro.config.ts"
# `index` is generated by website/scripts/sync-docs.ts, not carried in docs/.
GENERATED = {"index"}


def sidebar_slugs(text: str) -> list[str]:
    return re.findall(r"\{\s*slug:\s*'([^']+)'\s*\}", text)


def tracked_docs() -> set[str]:
    out = subprocess.run(
        ["git", "ls-files", "docs"], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.split()
    # Every depth: a slug is the path under docs/ without its suffix, so a
    # nested page like `adr/0001-two-executors` is named exactly as the
    # sidebar names it. Filtering to top level here is what made the first
    # version of this script accuse a committed ADR of being missing.
    return {p[len("docs/") : -len(".md")] for p in out if p.endswith(".md")}


def committed_config() -> str | None:
    """astro.config.ts as HEAD has it, or None if HEAD has no such file."""
    r = subprocess.run(
        ["git", "show", f"HEAD:{CONFIG.relative_to(ROOT)}"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return r.stdout if r.returncode == 0 else None


def worktree_docs() -> set[str]:
    return {str(q.relative_to(ROOT / "docs"))[: -len(".md")] for q in (ROOT / "docs").rglob("*.md")}


def disagreements(slugs: list[str], docs: set[str], committed: bool) -> list[str]:
    """Every way the two can fail to describe the same site."""
    out: list[str] = []
    for slug in (s for s in slugs if s not in docs and s not in GENERATED):
        if committed:
            local = (ROOT / "docs" / f"{slug}.md").exists()
            why = "exists locally but is NOT COMMITTED" if local else "does not exist"
        else:
            why = "does not exist"
        out.append(f"sidebar names '{slug}': docs/{slug}.md {why}")
    out += [
        f"docs/{d}.md exists but no sidebar entry reaches it" for d in sorted(docs - set(slugs))
    ]
    out += [
        f"sidebar names '{s}' more than once"
        for s in sorted({s for s in slugs if slugs.count(s) > 1})
    ]
    return out


def main() -> int:
    # BOTH states, because they answer different questions and this script got
    # it half right for a day: it judged docs by `git ls-files` and the sidebar
    # by the file on disk. A sidebar entry left uncommitted beside a committed
    # document therefore passed here and failed the build -- the working tree
    # reporting a laptop's state, which is the very thing this exists to catch.
    # See docs/11-ci.md, "The working tree is not the repository".
    checks = [("as committed (what CI builds)", committed_config(), tracked_docs())]
    if (disk := CONFIG.read_text()) != checks[0][1]:
        checks.append(("in the working tree (what you see)", disk, worktree_docs()))

    failed = False
    for label, config, docs in checks:
        if config is None:
            print(f"{label}: {CONFIG.relative_to(ROOT)} is not in HEAD -- commit it first.")
            failed = True
            continue
        slugs = sidebar_slugs(config)
        if not slugs:
            print(f"{label}: no sidebar slugs found -- has the config's shape changed?")
            failed = True
            continue
        problems = disagreements(slugs, docs, committed=label.startswith("as committed"))
        if problems:
            failed = True
            print(f"{label} -- {len(slugs)} sidebar entries, {len(docs)} documents:")
            for line in problems:
                print(f"  {line}")
        else:
            print(f"{label}: {len(docs)} pages, all reachable")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
